AWSTemplateFormatVersion: '2010-09-09'
Description: HAL LabSight ECR repository
Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: hal-labsight
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: IMMUTABLE
      EncryptionConfiguration:
        EncryptionType: AES256
Outputs:
  RepositoryUri:
    Value: !GetAtt Repository.RepositoryUri
